CHOICES = ('Warrior', 'Robber', 'Wizard')
STARTING_SCORE = 0
PLAYER_HEALTH = 3
DEFENCE_RESULT = ("YOUR DEFENCE IS SUCCESSFUL!", "YOUR DEFENCE IS FAILED!", "IT'S A DRAW!")
ATTACK_RESULT = ("YOUR ATTACK IS SUCCESSFUL!", "YOUR ATTACK IS FAILED!", "IT'S A DRAW!")
SCORE_FOR_AN_ENEMY = 5
