CHOICES = ('Warrior', 'Robber', 'Wizard')
RESULT_DICT = {'Warrior':'Robber', 'Robber':'Wizard', 'Wizard':'Warrior'}
RESULT_LST = ["IT'S A DRAW!", "YOUR ATTACK IS SUCCESSFUL!", "YOUR DEFENCE IS FAILED!", "YOUR ATTACK IS FAILED!", "YOUR DEFENCE IS SUCCESSFUL!"]
STARTING_SCORE = 0
PLAYER_HEALTH = 3
SCORE_FOR_AN_ENEMY = 5
